version: '3.5'

services:
  expo_android:
    container_name: expo_android
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes:
     - ./:/app/
     - /app/node_modules